# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitledRfJENN.ui'
##
## Created by: Qt User Interface Compiler version 5.15.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
from PySide2.QtWidgets import QApplication, QWidget
import sys

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitledhsanwS.ui'
##
## Created by: Qt User Interface Compiler version 5.15.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_CADERNETA(object):
    def setupUi(self, CADERNETA):
        if not CADERNETA.objectName():
            CADERNETA.setObjectName(u"CADERNETA")
        CADERNETA.resize(1000, 400)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CADERNETA.sizePolicy().hasHeightForWidth())
        CADERNETA.setSizePolicy(sizePolicy)
        CADERNETA.setMinimumSize(QSize(1000, 400))
        CADERNETA.setMaximumSize(QSize(1000, 300))
        icon = QIcon()
        icon.addFile(u"Captura de tela 2024-08-19 163021.png", QSize(), QIcon.Normal, QIcon.Off)
        CADERNETA.setWindowIcon(icon)
        CADERNETA.setAutoFillBackground(False)
        self.checkBox = QCheckBox(CADERNETA)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(190, 60, 131, 20))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy1)
        self.checkBox.setMinimumSize(QSize(0, 0))
        self.checkBox.setBaseSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setIconSize(QSize(100, 100))
        self.textBrowser_3 = QTextBrowser(CADERNETA)
        self.textBrowser_3.setObjectName(u"textBrowser_3")
        self.textBrowser_3.setGeometry(QRect(-210, 0, 1401, 301))
        sizePolicy1.setHeightForWidth(self.textBrowser_3.sizePolicy().hasHeightForWidth())
        self.textBrowser_3.setSizePolicy(sizePolicy1)
        self.checkBox_2 = QCheckBox(CADERNETA)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(190, 100, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_2.sizePolicy().hasHeightForWidth())
        self.checkBox_2.setSizePolicy(sizePolicy1)
        self.checkBox_2.setMinimumSize(QSize(0, 0))
        self.checkBox_2.setBaseSize(QSize(0, 0))
        self.checkBox_2.setFont(font)
        self.checkBox_2.setIconSize(QSize(100, 100))
        self.checkBox_3 = QCheckBox(CADERNETA)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(190, 140, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy1)
        self.checkBox_3.setMinimumSize(QSize(0, 0))
        self.checkBox_3.setBaseSize(QSize(0, 0))
        self.checkBox_3.setFont(font)
        self.checkBox_3.setIconSize(QSize(100, 100))
        self.checkBox_4 = QCheckBox(CADERNETA)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(190, 180, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy1)
        self.checkBox_4.setMinimumSize(QSize(0, 0))
        self.checkBox_4.setBaseSize(QSize(0, 0))
        self.checkBox_4.setFont(font)
        self.checkBox_4.setIconSize(QSize(100, 100))
        self.checkBox_5 = QCheckBox(CADERNETA)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setGeometry(QRect(190, 220, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_5.sizePolicy().hasHeightForWidth())
        self.checkBox_5.setSizePolicy(sizePolicy1)
        self.checkBox_5.setMinimumSize(QSize(0, 0))
        self.checkBox_5.setBaseSize(QSize(0, 0))
        self.checkBox_5.setFont(font)
        self.checkBox_5.setIconSize(QSize(100, 100))
        self.checkBox_16 = QCheckBox(CADERNETA)
        self.checkBox_16.setObjectName(u"checkBox_16")
        self.checkBox_16.setGeometry(QRect(190, 260, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_16.sizePolicy().hasHeightForWidth())
        self.checkBox_16.setSizePolicy(sizePolicy1)
        self.checkBox_16.setMinimumSize(QSize(0, 0))
        self.checkBox_16.setBaseSize(QSize(0, 0))
        self.checkBox_16.setFont(font)
        self.checkBox_16.setIconSize(QSize(100, 100))
        self.checkBox_6 = QCheckBox(CADERNETA)
        self.checkBox_6.setObjectName(u"checkBox_6")
        self.checkBox_6.setGeometry(QRect(410, 140, 191, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_6.sizePolicy().hasHeightForWidth())
        self.checkBox_6.setSizePolicy(sizePolicy1)
        self.checkBox_6.setMinimumSize(QSize(0, 0))
        self.checkBox_6.setBaseSize(QSize(0, 0))
        self.checkBox_6.setFont(font)
        self.checkBox_6.setIconSize(QSize(100, 100))
        self.checkBox_7 = QCheckBox(CADERNETA)
        self.checkBox_7.setObjectName(u"checkBox_7")
        self.checkBox_7.setGeometry(QRect(410, 220, 191, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_7.sizePolicy().hasHeightForWidth())
        self.checkBox_7.setSizePolicy(sizePolicy1)
        self.checkBox_7.setMinimumSize(QSize(0, 0))
        self.checkBox_7.setBaseSize(QSize(0, 0))
        self.checkBox_7.setFont(font)
        self.checkBox_7.setIconSize(QSize(100, 100))
        self.checkBox_8 = QCheckBox(CADERNETA)
        self.checkBox_8.setObjectName(u"checkBox_8")
        self.checkBox_8.setGeometry(QRect(410, 100, 201, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_8.sizePolicy().hasHeightForWidth())
        self.checkBox_8.setSizePolicy(sizePolicy1)
        self.checkBox_8.setMinimumSize(QSize(0, 0))
        self.checkBox_8.setBaseSize(QSize(0, 0))
        self.checkBox_8.setFont(font)
        self.checkBox_8.setIconSize(QSize(100, 100))
        self.checkBox_9 = QCheckBox(CADERNETA)
        self.checkBox_9.setObjectName(u"checkBox_9")
        self.checkBox_9.setGeometry(QRect(410, 180, 161, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_9.sizePolicy().hasHeightForWidth())
        self.checkBox_9.setSizePolicy(sizePolicy1)
        self.checkBox_9.setMinimumSize(QSize(0, 0))
        self.checkBox_9.setBaseSize(QSize(0, 0))
        self.checkBox_9.setFont(font)
        self.checkBox_9.setIconSize(QSize(100, 100))
        self.checkBox_17 = QCheckBox(CADERNETA)
        self.checkBox_17.setObjectName(u"checkBox_17")
        self.checkBox_17.setGeometry(QRect(410, 260, 211, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_17.sizePolicy().hasHeightForWidth())
        self.checkBox_17.setSizePolicy(sizePolicy1)
        self.checkBox_17.setMinimumSize(QSize(0, 0))
        self.checkBox_17.setBaseSize(QSize(0, 0))
        self.checkBox_17.setFont(font)
        self.checkBox_17.setIconSize(QSize(100, 100))
        self.checkBox_10 = QCheckBox(CADERNETA)
        self.checkBox_10.setObjectName(u"checkBox_10")
        self.checkBox_10.setGeometry(QRect(410, 60, 191, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_10.sizePolicy().hasHeightForWidth())
        self.checkBox_10.setSizePolicy(sizePolicy1)
        self.checkBox_10.setMinimumSize(QSize(0, 0))
        self.checkBox_10.setBaseSize(QSize(0, 0))
        self.checkBox_10.setFont(font)
        self.checkBox_10.setIconSize(QSize(100, 100))
        self.checkBox_11 = QCheckBox(CADERNETA)
        self.checkBox_11.setObjectName(u"checkBox_11")
        self.checkBox_11.setGeometry(QRect(670, 130, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_11.sizePolicy().hasHeightForWidth())
        self.checkBox_11.setSizePolicy(sizePolicy1)
        self.checkBox_11.setMinimumSize(QSize(0, 0))
        self.checkBox_11.setBaseSize(QSize(0, 0))
        self.checkBox_11.setFont(font)
        self.checkBox_11.setIconSize(QSize(100, 100))
        self.checkBox_12 = QCheckBox(CADERNETA)
        self.checkBox_12.setObjectName(u"checkBox_12")
        self.checkBox_12.setGeometry(QRect(670, 210, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_12.sizePolicy().hasHeightForWidth())
        self.checkBox_12.setSizePolicy(sizePolicy1)
        self.checkBox_12.setMinimumSize(QSize(0, 0))
        self.checkBox_12.setBaseSize(QSize(0, 0))
        self.checkBox_12.setFont(font)
        self.checkBox_12.setIconSize(QSize(100, 100))
        self.checkBox_13 = QCheckBox(CADERNETA)
        self.checkBox_13.setObjectName(u"checkBox_13")
        self.checkBox_13.setGeometry(QRect(670, 90, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_13.sizePolicy().hasHeightForWidth())
        self.checkBox_13.setSizePolicy(sizePolicy1)
        self.checkBox_13.setMinimumSize(QSize(0, 0))
        self.checkBox_13.setBaseSize(QSize(0, 0))
        self.checkBox_13.setFont(font)
        self.checkBox_13.setIconSize(QSize(100, 100))
        self.checkBox_14 = QCheckBox(CADERNETA)
        self.checkBox_14.setObjectName(u"checkBox_14")
        self.checkBox_14.setGeometry(QRect(670, 170, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_14.sizePolicy().hasHeightForWidth())
        self.checkBox_14.setSizePolicy(sizePolicy1)
        self.checkBox_14.setMinimumSize(QSize(0, 0))
        self.checkBox_14.setBaseSize(QSize(0, 0))
        self.checkBox_14.setFont(font)
        self.checkBox_14.setIconSize(QSize(100, 100))
        self.checkBox_18 = QCheckBox(CADERNETA)
        self.checkBox_18.setObjectName(u"checkBox_18")
        self.checkBox_18.setGeometry(QRect(670, 250, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_18.sizePolicy().hasHeightForWidth())
        self.checkBox_18.setSizePolicy(sizePolicy1)
        self.checkBox_18.setMinimumSize(QSize(0, 0))
        self.checkBox_18.setBaseSize(QSize(0, 0))
        self.checkBox_18.setFont(font)
        self.checkBox_18.setIconSize(QSize(100, 100))
        self.checkBox_15 = QCheckBox(CADERNETA)
        self.checkBox_15.setObjectName(u"checkBox_15")
        self.checkBox_15.setGeometry(QRect(670, 60, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_15.sizePolicy().hasHeightForWidth())
        self.checkBox_15.setSizePolicy(sizePolicy1)
        self.checkBox_15.setMinimumSize(QSize(0, 0))
        self.checkBox_15.setBaseSize(QSize(0, 0))
        self.checkBox_15.setFont(font)
        self.checkBox_15.setIconSize(QSize(100, 100))
        self.checkBox_19 = QCheckBox(CADERNETA)
        self.checkBox_19.setObjectName(u"checkBox_19")
        self.checkBox_19.setGeometry(QRect(190, 60, 131, 20))
        sizePolicy1.setHeightForWidth(self.checkBox_19.sizePolicy().hasHeightForWidth())
        self.checkBox_19.setSizePolicy(sizePolicy1)
        self.checkBox_19.setMinimumSize(QSize(0, 0))
        self.checkBox_19.setBaseSize(QSize(0, 0))
        self.checkBox_19.setFont(font)
        self.checkBox_19.setIconSize(QSize(100, 100))

        self.retranslateUi(CADERNETA)

        QMetaObject.connectSlotsByName(CADERNETA)
    # setupUi

    def retranslateUi(self, CADERNETA):
        CADERNETA.setWindowTitle(QCoreApplication.translate("CADERNETA", u"Caderneta do Detetive - Jogo", None))
        self.checkBox.setText(QCoreApplication.translate("CADERNETA", u"Biblioteca", None))
        self.textBrowser_3.setHtml(QCoreApplication.translate("CADERNETA", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Sans Serif'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">LOCAIS		ARMAS		SUSPEITOS</span></p></body></html>", None))
        self.checkBox_2.setText(QCoreApplication.translate("CADERNETA", u"Almox", None))
        self.checkBox_3.setText(QCoreApplication.translate("CADERNETA", u"Entrada", None))
        self.checkBox_4.setText(QCoreApplication.translate("CADERNETA", u"Cantina", None))
        self.checkBox_5.setText(QCoreApplication.translate("CADERNETA", u"Laboratorio", None))
        self.checkBox_16.setText(QCoreApplication.translate("CADERNETA", u"Banheiro", None))
        self.checkBox_6.setText(QCoreApplication.translate("CADERNETA", u"Faca", None))
        self.checkBox_7.setText(QCoreApplication.translate("CADERNETA", u"Livro de Eletr\u00f4nica", None))
        self.checkBox_8.setText(QCoreApplication.translate("CADERNETA", u"Chave de Fenda", None))
        self.checkBox_9.setText(QCoreApplication.translate("CADERNETA", u"Transformador", None))
        self.checkBox_17.setText(QCoreApplication.translate("CADERNETA", u"Soprador T\u00e9rmico", None))
        self.checkBox_10.setText(QCoreApplication.translate("CADERNETA", u"Ferro de Solda", None))
        self.checkBox_11.setText(QCoreApplication.translate("CADERNETA", u"Jo\u00e3o Pedro", None))
        self.checkBox_12.setText(QCoreApplication.translate("CADERNETA", u"Giovanna", None))
        self.checkBox_13.setText(QCoreApplication.translate("CADERNETA", u"Diana", None))
        self.checkBox_14.setText(QCoreApplication.translate("CADERNETA", u"Eduardo", None))
        self.checkBox_18.setText(QCoreApplication.translate("CADERNETA", u"Hugo", None))
        self.checkBox_15.setText(QCoreApplication.translate("CADERNETA", u"Thaine", None))
        self.checkBox_19.setText(QCoreApplication.translate("CADERNETA", u"Biblioteca", None))
    # retranslateUi






# Código principal para rodar a interface
if __name__ == "__main__":
    app = QApplication(sys.argv)
    Caderneta = QWidget()
    ui = Ui_CADERNETA()
    ui.setupUi(Caderneta)
    Caderneta.show()
    sys.exit(app.exec_())
